config/routes.rb
Spree::Core::Engine.add_routes do

  namespace :admin do
    resources :shipments
    post '/shipments/change_delivery_man', :to => 'shipments#change_delivery_man', :as => :admin_shipments_change_delivery_man
  	get '/shipments/shipment_delivery_man/:user_id', :to => 'shipments#shipment_delivery_man', :as => :admin_shipment_delivery_man
    post '/shipments/capture', :to => 'shipments#capture', :as => :admin_shipment_delivery_man_capture
  end

end

app/controllers/spree/admin/shipments_controller.rb
module Spree
  module Admin
    class ShipmentsController < Spree::Admin::ResourceController
      before_action :load_data, only: [:index]
      def index
        if params[:shipments].present? && params[:shipments][:time].present?
          @time=Dish::TimeFrame.find(params[:shipments][:time])
        end
      end

      def load_data
        @time = Dish::TimeFrame.first
        @deliverers = Spree::User.deliverers
      end

      def change_delivery_man
        if params[:shipment_id] && params[:user_id]
          shipment = Spree::Shipment.find(params[:shipment_id])
          user = Spree::User.find(params[:user_id])
          unless shipment.nil? && user.nil?
            shipment.user_id = user.id
            if shipment.save
              render json: { success: "ok" }, status: 200
            else
              render json: { error: "Could not save" }, status: 400
            end
          end
        end
      end

      def capture
        if params[:user_id] && params[:amount]
          user = Spree::User.find(params[:user_id])
          amount = BigDecimal.new params[:amount]
          if(user.balance> amount)
            user.balance = user.balance - amount
            if user.save
              render json: { success: "ok" }, status: 200
            else
              render json: { error: "Could not save" }, status: 400

            end
          else
            render json: { error: "Could not save" }, status: 400
          end
        end
      end

      def edit
        @addresses = @shipment.address.to_string
      end

      def shipment_delivery_man
        if params[:user_id].present?
          @deliverer = Spree::User.find(params[:user_id])
          @shipments = Spree::Shipment.optimize @deliverer.shipments.date(Date.today)
          #@shipments = Spree::Shipment.optimize @deliverer.shipments
          @addresses = []
          unless @shipments.nil?
            @shipments.reverse
            @shipments.each do |shipment|
              @addresses << shipment.address.to_string
            end
            
          end
        end
      end



      private

        def find_resource
          if parent_data.present?
            parent.send(controller_name).find_by!(number: params[:id])
          else
            model_class.find_by!(number: params[:id])
          end
        end
    end
  end
end

app/views/spree/admin/shipments/_google_script.html.erb
<script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCKVRDohw_WcFZi1JgghvZZBKJcjTbhQkI&sensor=false">
</script>

app/views/spree/admin/shipments/_shipment.html.erb
<div id="<%= "shipment_#{shipment.id}" %>" data-hook="admin_shipment_form" class="panel panel-default">

  <%= render partial: "spree/admin/variants/split", formats: :js %>

  <div class="panel-heading stock-location no-borderb" data-hook="stock-location">
    <h1 class="panel-title">
      <span class="shipment-number"><%= shipment.number %></span>
      -
      <span class="shipment-state"><%= Spree.t("shipment_states.#{shipment.state}") %></span>
      -<%= shipment.time_frame.name %> -
      <strong class="stock-location-name" data-hook="stock-location-name">'<%= shipment.date_delivery %>'</strong>
      <% if shipment.ready? and can? :update, shipment %>
        <%= link_to Spree.t(:ship), 'javascript:;', class: 'ship pull-right btn btn-success', data: { 'shipment-number' => shipment.number } %>
        <div class='clearfix'></div>
      <% end %>
    </h1>
  </div>

  <table class="table table-bordered stock-contents" data-hook="stock-contents">
    <thead>
      <th colspan="2"><%= Spree.t(:item_description) %></th>
      <th width="15%" class="text-center"><%= Spree.t(:price) %></th>
      <th width="15%" class="text-center"><%= Spree.t(:quantity) %></th>
      <th width="15%" class="text-center"><%= Spree.t(:total) %></th>
    </thead>

    <tbody data-shipment-number="<%= shipment.number %>" data-order-number="<%= order.number %>">
      <%= render 'shipment_manifest', shipment: shipment %>

      <% unless shipment.shipped? %>
        <tr class="edit-method is-hidden total">
          <td colspan="3">
            <div class="field alpha five columns">
              <%= label_tag 'selected_shipping_rate_id', Spree.t(:shipping_time) %>
              <%= select_tag :selected_shipping_rate_id,
                    options_for_select(Dish::TimeFrame.all.map {|sr| ["#{sr.name}", sr.id] }, shipment.time_frame_id),
                    { class: 'select2', data: {'shipment-number' => shipment.number } } %>
            </div>
          </td>
          <td colspan="2">
            <div class="field alpha five columns ">
                <%= label_tag 'shipping_rate_date_delivery', Spree.t(:shipping_date) %>
                <%= text_field :selected_shipping_rate_date_delivey,"", value: shipment.date_delivery, class: 'datepick form-control', id: shipment.number, data: {'shipment-number' => shipment.number }  %>    
            </div>
          </td>
          <td class="actions text-center">
            <% if can? :update, shipment %>
              <%= link_to_with_icon 'cancel', Spree.t('actions.cancel'), "#", class: 'cancel-method btn btn-primary btn-sm', data: {action: 'cancel'}, title: Spree.t('actions.cancel'), no_text: true %>
              <%= link_to_with_icon 'save', Spree.t('actions.save'), "#", class: 'save-method1 btn btn-success btn-sm', data: {'shipment-number' => shipment.number, action: 'save'}, title: Spree.t('actions.save'), no_text: true %>
            <% end %>
          </td>
        </tr>
        <% end %>

        <tr class="show-method total" style="text-align:center">
          <% if rate = shipment.selected_shipping_rate %>
            <td colspan="1">
              <strong>Time Delivery</strong>
            </td>
            <td colspan="1">
              <strong><%= shipment.date_delivery %></strong>
            </td>
            <td colspan="3">
              <strong><%= shipment.time_frame.name %></strong>
            </td>
          <% else %>
            <td colspan='5'><%= Spree.t(:no_shipping_method_selected) %></td>
          <% end %>
        
        </tr>
        <tr class="show-method total" style="text-align:center">
            <td colspan="1">
              <strong><%= Spree.t(:customer_information) %></strong>
            </td>
            <td colspan="1">
              <strong><%= Spree.t(:Name) %>: <%= shipment.order.ship_address.last_name %> <%= shipment.order.ship_address.last_name %></strong>
            </td>
            <td colspan="3">
              <strong><%= Spree.t(:Address) %>: 
              <%= shipment.order.ship_address.address1 %>, <%= shipment.order.ship_address.city %></strong>
            </td>
        </tr>

    </tbody>
  </table>

</div>
<script type="text/javascript">
   $('.datepick').each(function(){
    $(this).datepicker({ dateFormat: 'yy-mm-dd' });
});

</script>

app/views/spree/admin/shipments/_shipment_index.html.erb
 <td><%= link_to shipment.number, spree.edit_admin_shipment_path(shipment) %></td>
<td><span class="state <%= shipment.state.downcase %>"><%= Spree.t("shipment_state.#{shipment.state.downcase}") %></span></td>
<td> <%= shipment.display_item_cost.to_html %></td>
<td> 
  <%= Spree.t(:Name) %>: <%= shipment.order.ship_address.last_name %> <%= shipment.order.ship_address.last_name %>
  <br>
  <%= Spree.t(:Address) %>: <%= shipment.order.ship_address.address1 %>, <%= shipment.order.ship_address.city %>
</td>

<td data-hook="admin_shipments_index_row_actions">
  <%= link_to_edit_url spree.edit_admin_shipment_path(shipment), :title => "admin_edit_#{dom_id(shipment)}", :no_text => true %>
</td>

app/views/spree/admin/shipments/_shipment_manifest.html.erb
<% shipment.manifest.each do |item| %>
  <tr class="stock-item" data-item-quantity="<%= item.quantity %>">
    <td class="item-image image text-center">
      <%= mini_image(item.variant) %>
    </td>

    <td class="item-name">
      <%= truncate(item.variant.product.name , escape: false,length: 20) %>
    </td>

    <td class="item-price text-center"><%= item.line_item.single_money.to_html %></td>

    <td class="item-qty-show text-center">
      <% item.states.each do |state,count| %>
        <%= count %> x <%= Spree.t(state).downcase %>
      <% end %>
    </td>

    <% unless shipment.shipped? %>
      <td class="item-qty-edit is-hidden">
        <%= number_field_tag :quantity, item.quantity, min: 0, class: "line_item_quantity form-control", size: 5 %>
      </td>
    <% end %>

    <td class="item-total text-center">
      <%= line_item_shipment_price(item.line_item, item.quantity) %>
    </td>

  </tr>
<% end %>

app/views/spree/admin/shipments/edit.html.erb
<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:back_to_shipments_list), spree.admin_shipments_path, icon: 'arrow-left' %>
<% end %>

<div>
	<div class="col-md-4">
		<div data-hook="edit_image" class="panel panel-default">
    <div class="panel-heading">
      <h1 class="panel-title">
      	<%= Spree.t(:delivery_man) %>
      </h1>
      <div class="pull-right" style="margin-top: -28px;">
      	<a class="change  btn btn-primary">Change</a>
      </div>
    </div>
    <div class="panel-body">
      <div class="form-group">
        <div data-hook="thumbnail" class="col-md-5 text-center">
        <%if @shipment.deliverer.images.any? %>
          <%= image_tag @shipment.deliverer.images.first.attachment.url(:normal) %>
        <% end %>
        </div>
        <div class="col-md-7">
        	<b><%= Spree.t(:Name) %>: </b><%= @shipment.deliverer.first_name %> <%= @shipment.deliverer.last_name %>
        	<br>
        	<b><%= Spree.t(:email) %>: </b><%= @shipment.deliverer.email %>
        </div>
        </div>
        <div class="form-buttons filter-actions actions" data-hook="buttons">
        </div>
      </div>
    </div>
    <div class="change_delivery" style="display:none">
  	<%=  collection_select(:user, :user_id, Spree::User.deliverers, :id, :email, {:selected => @shipment.deliverer.id},{:class => ' select2'}) %>
    </div>
  </div>
  
	</div>
	<div data-hook="admin_shipment_form_fields" class="col-md-8">
	  <%= render partial: "shipment", locals: { order: @shipment.order, shipment: @shipment } %>
	</div>
</div>

<div id="map-canvas" style="width:800px;height:600px;margin: 0 auto;top:35px"/>
<div id="directions-panel"></div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    var company_address = "<%= COMPANY_ADDRESS %>";
    var addresses = [];
      addresses.push({
         location: "<%= @addresses %>",
         stopover: true
       });
    console.log(addresses[addresses.length -1]);
    initMap(company_address,addresses)
  });
</script>


<script type="text/javascript">
   
  $(".change").click(function() {
   	$(".change_delivery").show();
  });

  $('.change_delivery .select2').on('change', function() {
   	var shipment_id =<%= @shipment.id %>
   	var user_id = $(this).val();
   	$.ajax({
        type: 'POST',
        dataType: 'json',
        url: '/admin/shipments/change_delivery_man',
        data: {
        	"shipment_id":shipment_id,
          "user_id": user_id
        },
        success: function(data) {
          window.location.reload();
        },
        error: function(jqXHR, textStatus, errorThrown) {
          alert("An error occurred while trying to update the deliverer. Please try again.");
        }
      });
 	});
</script>

app/views/spree/admin/shipments/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:listing_shipments) %>
<% end %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:search) %>
<% end %>
<div class="form-group col-md-12">
  <%= form_for "shipments", url: admin_shipments_url, method: 'Get', html: { id: "shipments", multipart: true } do |f|%>
  <div class="shipment-filter col-md-3">
      <div class="form-group col-md-12">
        <%= f.collection_select "time", Dish::TimeFrame.all, :id, :name, {:include_blank => false,:selected => @time.id.to_i},  {:class => 'form-control',:data=>@time.id.to_i} %>
      </div>
  </div>
  <%= submit_tag 'APPLY',  :class => "btn btn-success", data: {  }%>
<% end %>

</div>


<% unless @shipments.empty? %>
  <table class="table" id="listing_shipments" data-hook>
    <thead>
      <tr data-hook="admin_orders_index_headers">
        <th><%= Spree.t(:delivery_man) %></th>
        <th><%= Spree.t(:shipment_number) %></th>
        <th><%= Spree.t(:shipment_state) %></th>
        <th><%= Spree.t(:item_cost) %></th>
        <th> <%= Spree.t(:customer_information) %></th>
        <th data-hook="admin_shipments_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
    <% @deliverers.each do |deliverer| %>
      <tr data-hook="admin_shipments_index_rows" class="">
         <% shipments = deliverer.shipments.date(Date.today).time_frame(@time.id)%>
        <td rowspan="<%= count = shipments.count%>">
          <a href="/admin/shipments/shipment_delivery_man/<%= deliverer.id %>">
            <%= deliverer.first_name %> <%= deliverer.last_name %>
          </a> 
        </td>
        <% unless count == 0 %>
       

          <%= render :partial => 'spree/admin/shipments/shipment_index', :locals => { :shipment => shipments.first } %>

      </tr>
          <% shipments =shipments.drop(1) %>
          <% shipments.each do |shipment| %>
      <tr data-hook="admin_shipments_index_rows" class="">
          <%= render :partial => 'spree/admin/shipments/shipment_index', :locals => { :shipment => shipment } %>
      </tr>
          <% end %>
        <% else %>
        </tr>
        <% end %>
    <% end %>
    </tbody>
  </table>
<% else %>
    <%# New alert 'Not Found' with i18n %>
      <%= Spree.t(:no_resource_found, resource: Spree::Shipment.model_name.human(count: :many)) %>
<% end %>

app/views/spree/admin/shipments/shipment_delivery_man.html.erb
<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:back_to_shipments_list), spree.admin_shipments_path, icon: 'arrow-left' %>
<% end %>

<div>
	<div class="col-md-4">
		<div data-hook="edit_image" class="panel panel-default">
    <div class="panel-heading">
      <h1 class="panel-title">
      	<%= Spree.t(:delivery_man) %>
      </h1>
      <div class="pull-right" style="margin-top: -28px;">
        <a class="capture btn btn-primary">Capture</a>
      </div>
    </div>
    <div class="panel-body">
      <div class="form-group">
        <div data-hook="thumbnail" class="col-md-5 text-center">
        <%if @deliverer.images.any? %>
          <%= image_tag @deliverer.images.first.attachment.url(:normal) %>
        <% end %>
        </div>

        <div class="col-md-7">
        	<b><%= Spree.t(:Name) %>: </b><%= @deliverer.first_name %> <%= @deliverer.last_name %>
        	<br>
        	<b><%= Spree.t(:email) %>: </b><%= @deliverer.email %>
          <br>
          <b><%= Spree.t(:income) %>: </b><%= number_to_currency(@deliverer.balance, :unit => '', precision: 0, seperator: ".", format: "%n %u") rescue '' %>  
        </div>
        
        </div>
      </div>
    </div>
    <div class="capture_delivery" style="display:none">
      <form role="form">
        <div class="form-group">
          <label for="email">amount:</label>
          <input type="number" class="form-control" value="<%= @deliverer.balance %>" >
        </div>
        <button type="submit" class="btn btn-capture btn-default">Capture</button>
       </form>
    </div>
  
	</div>

  <div class="col-md-8">
  <% if @shipments.any? %>
    <% @shipments.each do |shipment| %>
    <div data-hook="admin_shipment_form_fields" >
    <%= render partial: "shipment", locals: { order: shipment.order, shipment: shipment } %>
    </div>
    <% end %>
  <% else %> 
     <div class="alert alert-info no-objects-found">
      <%= Spree.t(:no_shipments_today) %>
    </div>
  <% end %>
  </div>
<% if @shipments.any? %>
  <div id="map-canvas" style="width:800px;height:600px;margin: 0 auto;top:35px"/>
  <div id="directions-panel"></div>
  </div>

  <script type="text/javascript">
    $(document).ready(function(){
      var company_address = "<%= COMPANY_ADDRESS %>";
      var addresses = [];
      <% @addresses.each do |address| %>
        addresses.push({
           location: "<%= address %>",
           stopover: true
         });
      <% end %>
      initMap(company_address,addresses);
    });

   

  </script>
<% end %>
  <script type="text/javascript">

  $(".capture").click(function() {
    $(".capture_delivery").show();
  });
  
  $(".btn-capture").click(function(event) {
    event.preventDefault();
    var amount = $('input[type="number"]').val();
    $.ajax({
        type: 'POST',
        dataType: 'json',
        url: '/admin/shipments/capture',
        data: {
          "user_id": <%=@deliverer.id%>,
          "amount": amount
        },
        success: function(data) {
          window.location.reload();
        },
        error: function(jqXHR, textStatus, errorThrown) {
          alert("An error occurred while trying to update the deliverer. Please try again.");
        }
      });

  });

</script>